### ISSUE TITLE
Category theory playlist in videos.md link not working

### ISSUE THREAD

**Issue by mazenamr** [dmvaldman/library#1]
Following the [category theory](https://www.youtube.com/playlist?list=PLbgaMIhjbmEnaH_LTkxLI7FMa2HsnawM) link in the [videos.md](https://github.com/dmvaldman/library/blob/master/videos.md) file leads to a YouTube page saying _Invalid Parameters._
![Invalid Parameters](https://user-images.githubusercontent.com/14795777/27864560-650792fe-618f-11e7-816d-a6475d29f3c8.png)

**Comment by dmvaldman** [comment]
Thanks, should work now. The correct link is: https://www.youtube.com/watch?v=I8LbkfSSR58&list=PLbgaMIhjbmEnaH_LTkxLI7FMa2HsnawM_
